Repository royxk/codeit_team5_project, pull requests merged in 2024-04, with the labels that each got.

#3 [PTTF-7] ✨ Test Pr branch
  src/app/page.tsx
Labels: Feat

#4 [PTTF-8] ✨ testBranch3
  src/app/test/page.tsx
Labels: Feat

#6 [PTTF-26] ✨ 폴더 구조 설정
  components/common/Input.tsx
  src/app/employee/page.tsx
  src/app/employer/page.tsx
  src/app/page.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
Labels: Feat

#8 [PTTF-11] global css
  src/app/cssTest/page.tsx
  tailwind.config.ts
Labels: Feat

#7 [PTTF-25] ✨ 폴더 구조 변경점
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/Input.tsx
  src/util/api.ts
Labels: Feat

#9 [PTTF-27] Tailwind setting
  src/app/cssTest/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
Labels: Feat

#10 [PTTF-17] input 컴포넌트
  public/dropdown.svg
  src/components/common/Input.tsx
  src/util/constants/INPUT_VALUES.ts
Labels: Feat

#12 [PTTF-29] tailwind Prettier 자동정렬 세팅
  package-lock.json
  package.json
  prettier.config.js
Labels: documentation

#11 [PTTF-21] Table 컴포넌트 구현
  src/components/common/Table.tsx
Labels: Feat

#16 [PTTF-12] api 설정
  apiTest.http
  package-lock.json
  package.json
  src/app/apiTest/page.tsx
  src/app/btnTest/page.tsx
  src/components/common/Button.tsx
  src/util/api.ts
  src/util/constants/API_VALUES.ts
  src/util/cookieSetting.ts
  tailwind.config.ts
Labels: Feat

#18 [PTTF-33] Footer ui 작성
  public/footer/facebook.svg
  public/footer/gmail.svg
  public/footer/instagram.svg
  src/components/common/Footer.tsx
Labels: Feat

#20 [PTTF-13] 버튼 컴포넌트 작성
  src/app/btnTest/page.tsx
  src/components/common/Button.tsx
Labels: Feat

#15 [PTTF-32] 글자 크기별 기본 css tailwindClass 형식으로 사전 작성
  src/app/globals.css
Labels: documentation

#22 ♻️ 반응형 미디어쿼리를 extend 내부로 이동, pc제거 및 tab과 mob 수정
  tailwind.config.ts
Labels: Fix

#24 [PTTF-37] footer layout 수정
  src/components/common/Footer.tsx
Labels: Fix

#25 [PTTF-38] 버튼 컴포넌트 수정
  src/components/common/Button.tsx
  tailwind.config.ts
Labels: Fix

#26 [PTTF-36] ✨ 공통 레이아웃 지정
  src/app/layout.tsx
Labels: Feat

#28 [PTTF-39] ♻️ Link 태그에 target blank 코드 추가
  src/components/common/Footer.tsx
Labels: Refactor

#21 [PTTF-20] ✨ Notification Modal Component Added
  public/NotificationModal/statusfalse.svg
  public/NotificationModal/statustrue.svg
  src/app/notificationTest/page.tsx
  src/components/common/NotificationModal/NotificationModal.tsx
  src/components/common/NotificationModal/NotificationModalMessageBox.tsx
  src/util/constants/NOTIFICATION_MODAL_MOCK_DATA.ts
Labels: Feat

#17 [PTTF-28] Post Component 제작
  public/post/arrow.svg
  public/post/arrowsmall.svg
  public/post/location.svg
  public/post/testImg.svg
  public/post/time.svg
  src/app/page.tsx
  src/app/postTest/page.tsx
  src/components/common/Post/Post.tsx
  src/components/common/Post/SvgComponent.tsx
  src/util/constants/TEST_POST_VALUES.ts
  tailwind.config.ts
Labels: documentation, Feat

#29 [PTTF-41] Pagination, StatusLabel, Table 컴포넌트 연결
  src/components/common/ApproveButtons.tsx
  src/components/common/EmployeeTable.tsx
  src/components/common/EmployerTable.tsx
  src/components/common/Pagination.tsx
  src/components/common/StatusLabel.tsx
  src/components/common/Table.tsx
  src/util/constants/table_mock_data.ts
  src/util/convertData.ts
Labels: Feat, Refactor

#35 [PTTF-46] 🐛 Fix Svg Ui sizing
  next.config.mjs
  src/components/common/Post/Post.tsx
  src/components/common/Post/SvgArrowComponent.tsx
  src/components/common/Post/SvgComponent.tsx
  src/components/common/Post/SvgLocationComponent.tsx
  src/components/common/Post/SvgTimeComponent.tsx
  src/components/common/Post/Tooltip.tsx
Labels: Fix

#36 [PTTF-16] ✨ Add GNB component
  public/logoIcon.png
  public/notification_active.png
  public/notification_inactive.png
  public/searchIcon.png
  src/components/common/GNB.tsx
Labels: Feat

#30 [PTTF-23] ✨ Add filter components
  public/advancedFilter/closeFilter.svg
  src/app/filterTest/page.tsx
  src/components/common/AdvancedFilter/AdvancedFilter.tsx
  src/components/common/AdvancedFilter/AdvancedFilterComponent.tsx
  src/components/common/AdvancedFilter/LocationBox.tsx
  src/components/common/AdvancedFilter/SelectedLocationBox.tsx
  src/components/common/AdvancedFilter/SvgCloseButton.tsx
  src/components/common/NotificationModal/NotificationModal.tsx
  src/components/common/Post/Post.tsx
Labels: Feat

#39 [PTTF-47] ✨ Add skeleton UI
  src/app/postTest/page.tsx
  src/components/common/Post/PostSkeleton.tsx
Labels: Feat

#34 [PTTF-40] 공고 상세 / 가게 상세 페이지에서의 가게 정보 컴포넌트
  next.config.mjs
  public/store-detail-sample/unsplash.png
  src/app/employer/storeDetailTest/page.tsx
  src/app/globals.css
  src/app/storeDetailTest/page.tsx
  src/components/common/StoreDetail/StoreDetailButtons.tsx
  src/components/common/StoreDetail/StoreDetailCardBorder.tsx
  src/components/common/StoreDetail/StoreDetailTypes.ts
  src/components/common/StoreDetail/index.tsx
  src/util/constants/STORE_DETAIL_ASSIGNED.ts
  src/util/constants/STORE_DETAIL_EMPLOYER.ts
  src/util/constants/STORE_DETAIL_POST.ts
Labels: Feat

#41 [PTTF-45] 메인 페이지 UI 작업
  next.config.mjs
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/components/home/BasicFilter.tsx
  src/components/home/BasicFilterArrow.tsx
  src/components/home/CustomNotice.tsx
  src/components/home/FilterdNotice.tsx
  src/components/home/NoticeMain.tsx
  src/util/constants/FILTER_VALUES.ts
  src/util/formatDate.ts
  tailwind.config.ts
Labels: Feat

#42 [PTTF-48] GNB 레이아웃 적용
  src/app/layout.tsx
Labels: Feat

#43 [PTTF-49] ✅ Update Svg files and notification component
  public/NotificationModal/close.svg
  public/NotificationModal/notificationButton.svg
  public/NotificationModal/notificationButtonTrue.svg
  public/NotificationModal/status.svg
  public/NotificationModal/statusfalse.svg
  src/app/notificationTest/page.tsx
  src/components/common/AdvancedFilter/AdvancedFilterComponent.tsx
  src/components/common/NotificationModal/NotificationModal.tsx
  src/components/common/NotificationModal/NotificationModalComponent.tsx
  src/components/common/NotificationModal/NotificationModalMessageBox.tsx
  src/components/common/NotificationModal/SvgCloseComponent.tsx
  src/components/common/NotificationModal/SvgNotificationButton.tsx
  src/components/common/NotificationModal/SvgStatusComponent.tsx
Labels: Feat, Fix

#40 [PTTF-42] [일반 회원] 내 프로필 상세/등록 페이지 UI 구현
  public/Icon_phone.svg
  public/close.svg
  src/app/employee/my-profile/page.tsx
  src/app/employee/page.tsx
  src/components/common/Table.tsx
  src/util/constants/INPUT_VALUES.ts
  src/util/constants/PROFILE_PAGE_USER_TEST_DATA.ts
Labels: Feat

#37 [FTTP-22] ✨ Add Toast Component
  src/app/test/page.tsx
  src/components/common/Toast.tsx
Labels: Feat

#38 [PTTF-19] ✨ Add Modal Component
  public/checkIcon.png
  public/circleIcon.png
  public/exclamation_markIcon.png
  src/components/common/Modal.tsx
Labels: Feat

#44 [PTTF-52] POST 스켈레톤 UI 사이즈 및 수정
  src/app/postTest/page.tsx
  src/components/common/Post/Post.tsx
  src/components/common/Post/PostSkeleton.tsx
Labels: Fix

#47 [PTTF-56] Table 컴포넌트 높이 고정 및 반응형 디자인 추가
  package-lock.json
  package.json
  src/app/tableTest/page.tsx
  src/components/common/ApproveButtons.tsx
  src/components/common/StatusLabel.tsx
  src/components/common/Table.tsx
  src/components/common/TableHeader.tsx
Labels: Fix, Refactor

#48 [PTTF-51] GNB 수정
  src/app/layout.tsx
  src/components/common/GNB.tsx
  src/components/common/GNB/LogoSvg.tsx
  src/components/common/GNB/SearchSvg.tsx
Labels: Fix

#52 [PTTF-62] 공고상세페이지 / notification modal / advanced filter modal 수정
  src/app/apiTest/page.tsx
  src/app/noticeDetail/[noticeId]/[shopId]/page.tsx
  src/app/noticeDetail/page.tsx
  src/app/notificationTest/page.tsx
  src/components/common/AdvancedFilter/AdvancedFilter.tsx
  src/components/common/AdvancedFilter/AdvancedFilterComponent.tsx
  src/components/common/NotificationModal/NotificationModal.tsx
  src/components/common/NotificationModal/NotificationModalComponent.tsx
  src/components/common/Post/Post.tsx
  src/components/common/Post/PostListType.ts
  src/components/common/StoreDetail/index.tsx
Labels: Feat, Fix

#50 [PTTF-61] 사장 페이지 index 기본 작성
  next.config.mjs
  src/app/employer/page.tsx
  src/components/common/StoreDetail/index.tsx
Labels: Feat

#53 [PTTF-64] 🚑 fix minor issue
  src/components/common/AdvancedFilter/AdvancedFilterComponent.tsx
Labels: Feat, Fix

#56 [PTTF-68] jsx로 작성된 svg파일들의 에러 제거
  src/components/common/GNB/SearchSvg.tsx
  src/components/common/NotificationModal/SvgNotificationButton.tsx
  src/components/common/Post/SvgTimeComponent.tsx
Labels: Fix

#54 [PTTF-66] 사장이 등록한 공고 무한 스크롤 컴포넌트 및 사장페이지 일부 버그 수정
  src/app/employer/page.tsx
  src/app/employer/postTest/page.tsx
  src/components/common/StoreDetail/StoreDetailButtons.tsx
  src/components/employer/PostEmployer.tsx
  src/util/constants/EMPLOYER_POST_LIST.ts
Labels: Feat

#55 [PTTF-67] ✨ Local Storage Utils / 가게 상세 페이지 최근에 본 공고 local storage util 추가
  src/app/noticeDetail/page.tsx
  src/app/postTest/page.tsx
  src/components/common/StoreDetail/index.tsx
  src/util/recentPostsLocalStorageLogic.ts
Labels: Feat, Fix

#49 [PTTF-60] 가게 등록 페이지 작성
  public/icons/close.svg
  public/require-image.svg
  src/app/employer/register/page.tsx
  src/components/common/Input.tsx
  src/components/employer/StoreRegisterForm.tsx
  src/util/constants/INPUT_VALUES.ts
Labels: Feat

#58 [PTTF-69] noticeID/shopid 개별 로딩 완료
  src/app/noticeDetail/[noticeId]/[shopId]/page.tsx
  src/app/noticeDetail/page.tsx
  src/components/common/StoreDetail/index.tsx
  src/util/constants/STORE_DETAIL_POST.ts
  src/util/recentPostsLocalStorageLogic.ts
Labels: Feat, Fix

#60 [PTTF-43] 일반 회원 내 프로필 상세/등록 페이지 api 함수 연동
  src/app/employee/my-profile/page.tsx
  src/app/employee/page.tsx
  src/components/ProfileDetail/profileHeader.tsx
  src/util/constants/PROFILE_PAGE_USER_TEST_DATA.ts
  src/util/constants/table_mock_data.ts
Labels: Feat, Fix

#46 [PTTF58] ✨ Signin Page UI Added
  public/logoIcon.png
  public/signin/logoIcon.png
  public/signup/checkIcon.png
  public/signup/circleCheckIcon.png
  public/signup/grayCircleIcon.png
  public/signup/logoIcon.png
  public/signup/orangeCircleIcon.png
  src/app/signin/page.tsx
  src/components/common/Input.tsx
  src/components/common/Modal.tsx
  src/components/signin/EmailInput.tsx
  src/components/signin/Input.tsx
  src/components/signin/Modal.tsx
  src/components/signin/PasswordInput.tsx
Labels: Feat

#59 [PTTF-70] 메인페이지 필터 관련 여러 변경사항 적용
  apiTest.http
  next.config.mjs
  src/app/page.tsx
  src/components/common/Pagination.tsx
  src/components/common/Post/Post.tsx
  src/components/common/Table.tsx
  src/components/home/BasicFilter.tsx
  src/components/home/CustomNotice.tsx
  src/components/home/FilterdNotice.tsx
  src/components/home/NoticeMain.tsx
  src/util/convertData.ts
Labels: Feat, Refactor

#45 [PTTF59] ✨ Signup Page UI Added
  src/app/signup/page.tsx
  src/components/signup/ConfirmPasswordInput.tsx
  src/components/signup/EmailInput.tsx
  src/components/signup/Input.tsx
  src/components/signup/Modal.tsx
  src/components/signup/PasswordInput.tsx
Labels: Feat

#63 [PTTF-74] 💄 body 전체 padding의 변경으로 인한 반응형 디자인 수정
  src/components/common/Footer.tsx
Labels: Fix

#67 [PTTF-76] 사장 페이지의 공고 등록 및 수정 관련 기능
  src/app/employer/notice/[noticeId]/edit/page.tsx
  src/app/employer/notice/[noticeId]/page.tsx
  src/app/employer/notice/page.tsx
  src/components/employer/EmployerNoticeForm.tsx
  src/components/employer/FormCloseButton.tsx
  src/components/employer/StoreRegisterForm.tsx
  src/util/constants/INPUT_VALUES.ts
Labels: Feat

#70 [PTTF-79] Pagination 버그 픽스
  src/app/paginationTest/page.tsx
  src/components/common/Pagination.tsx
Labels: Fix

#65 [PTTF-73] ✨ 메인페이지에서 상세페이지 링크 local storage 추가 & 로직 변경 + UI 수정
  src/app/noticeDetail/[noticeId]/[shopId]/page.tsx
  src/app/noticeDetail/page.tsx
  src/app/page.tsx
  src/app/postTest/page.tsx
  src/components/common/Post/Post.tsx
  src/components/common/Post/PostListType.ts
  src/components/employer/PostEmployer.tsx
  src/components/home/CustomNotice.tsx
  src/components/home/FilterdNotice.tsx
  src/util/recentPostsLocalStorageLogic.ts
  ~
Labels: Feat, Fix

#68 [PTTF-77] ✨ notification modal mock 데이터로 테스트 완료
  src/app/notificationTest/page.tsx
  src/components/common/GNB.tsx
  src/components/common/NotificationModal/NOTIFICATION_API_RESPONSE_TYPE.ts
  src/components/common/NotificationModal/NotificationModal.tsx
  src/components/common/NotificationModal/NotificationModalComponent.tsx
  src/components/common/NotificationModal/NotificationModalMessageBox.tsx
Labels: Feat, Fix

#66 [PTTF-72] table 컴포넌트 재수정 및 ApproveButtons 컴포넌트 수정
  src/app/employee/page.tsx
  src/components/ProfileDetail/profileHeader.tsx
  src/components/common/ApproveButtons.tsx
  src/components/common/EmployeeTable.tsx
  src/components/common/EmployerTable.tsx
  src/components/common/Table.tsx
  src/util/convertData.ts
Labels: Fix

#69 [PTTF-78] 메인 페이지 상세필터 작업
  apiTest.http
  src/app/filterTest/page.tsx
  src/components/common/AdvancedFilter/AdvancedFilter.tsx
  src/components/common/AdvancedFilter/AdvancedFilterCloseSvg.tsx
  src/components/common/AdvancedFilter/AdvancedFilterComponent.tsx
  src/components/common/AdvancedFilter/LocationBox.tsx
  src/components/common/AdvancedFilter/SelectedLocationBox.tsx
  src/components/common/Pagination.tsx
  src/components/home/BasicFilter.tsx
  src/components/home/CustomNotice.tsx
  src/components/home/FilterdNotice.tsx
  src/components/home/NoticeMain.tsx
  src/util/api.ts
  src/util/convertData.ts
  src/util/formatDate.ts
Labels: Feat, Fix, Refactor

#71 [PTTF-81] 유저 타입에 따른 버튼 차별화 및 공고 신청 및 취소 기능
  src/components/common/StoreDetail/StoreDetailButtons.tsx
  src/components/common/StoreDetail/index.tsx
Labels: Feat

#74 [PTTF-83] search 페이지 deploy 오류 해결
  src/app/search/layout.tsx
  src/app/search/page.tsx
  src/components/home/FilterdNotice.tsx
  src/components/home/NoticeMain.tsx
Labels: Fix

#76 [PTTF-82] ✨GNB 버튼에 링크 추가
  src/components/common/GNB.tsx
Labels: Feat

#77 [PTTF-85] ♻️ 불필요한 count 제거
  src/components/home/FilterdNotice.tsx
Labels: Refactor

#78 [PTTF-87] ✨ 로그인 회원가입페이지 로그인 회원가입 기능 추가, 오류 수정
  public/circleIcon.png
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/common/ApproveButtons.tsx
  src/components/common/SignInput.tsx
  src/components/common/SignModal.tsx
  src/components/signin/EmailInput.tsx
  src/components/signin/Modal.tsx
  src/components/signin/PasswordInput.tsx
  src/components/signup/ConfirmPasswordInput.tsx
  src/components/signup/EmailInput.tsx
  src/components/signup/Input.tsx
  src/components/signup/Modal.tsx
  src/components/signup/PasswordInput.tsx
Labels: Feat, Fix

#75 [PTTF-84] 사장의 공고 상세 페이지 작성
  src/app/employer/notice/[noticeId]/page.tsx
  src/components/common/EmployerTable.tsx
  src/components/common/StoreDetail/StoreDetailButtons.tsx
  src/components/employer/EmployerNoticeDetail.tsx
  src/components/employer/EmployerNoticeForm.tsx
  src/components/employer/Hook/useNoticeId.tsx
  src/util/convertData.ts
Labels: Feat

#79 [PTTF-86] 사장 페이지 스타일 에러 및 담당 컴포넌트 종합 수정
  src/app/employer/page.tsx
  src/app/paginationTest/page.tsx
  src/app/storeDetailTest/page.tsx
  src/components/common/Input.tsx
  src/components/common/StoreDetail/StoreDetailButtons.tsx
  src/components/employer/EmployerNoticeForm.tsx
  src/components/employer/PostEmployer.tsx
  src/components/employer/StoreEditForm.tsx
  src/components/employer/StoreRegisterForm.tsx
  src/util/constants/INPUT_VALUES.ts
Labels: Fix

#82 [PTTF-89] 내 프로필 페이지 수정 및 ApproveButtons 컴포넌트 수정
  src/app/employee/my-profile/page.tsx
  src/components/ProfileDetail/profileHeader.tsx
  src/components/common/ApproveButtons.tsx
  src/components/common/EmployeeTable.tsx
  src/util/constants/INPUT_VALUES.ts
  src/util/convertData.ts
  src/util/formatPhoneNumber.ts
Labels: Feat, Fix, Refactor

#81 [PTTF-90] 로그인 및 회원가입 수정
  src/app/layout.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/common/Button.tsx
  src/components/common/GNB.tsx
  src/components/common/ModalPortal.tsx
  src/components/common/SignModal.tsx
  src/components/signin/EmailInput.tsx
  src/components/signin/PasswordInput.tsx
  src/components/signup/ConfirmPasswordInput.tsx
  src/components/signup/EmailInput.tsx
  src/components/signup/PasswordInput.tsx
Labels: Fix

#83 [PTTF-91] 상세 필터에 날짜 선택 시 발생하던 오류 제거
  src/components/common/AdvancedFilter/AdvancedFilter.tsx
  src/components/home/FilterdNotice.tsx
  src/util/formatDate.ts
Labels: Fix

#89 [PTTF-97] feat: 모달창 enter키 이벤트 추가, Input css 수정
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/common/SignInput.tsx
Labels: Feat, Fix

#87 [PTTF-96] Notification api 알림 API 연동완료
  src/components/ProfileDetail/profileHeader.tsx
  src/components/common/GNB.tsx
  src/components/common/NotificationModal/NotificationModal.tsx
  src/components/common/NotificationModal/NotificationModalComponent.tsx
  src/components/common/NotificationModal/NotificationModalMessageBox.tsx
  src/components/common/Post/Post.tsx
  src/components/common/StoreDetail/StoreDetailButtons.tsx
  src/components/employer/EmployerNoticeForm.tsx
  src/components/employer/StoreRegisterForm.tsx
  src/util/api.ts
  src/util/constants/API_VALUES.ts
  src/util/eplapsedTime.ts
Labels: Feat, Fix

#85 [PTTF-92] 맞춤공고에 맞는 데이터 보이도록 수정 및 상세필터 날짜 관련 함수 수정
  src/components/common/AdvancedFilter/AdvancedFilter.tsx
  src/components/common/AdvancedFilter/LocationBox.tsx
  src/components/home/CustomNotice.tsx
  src/components/home/FilterdNotice.tsx
  src/util/formatDate.ts
Labels: Feat

#90 [PTTF-98] middleware 생성
  src/app/signin/page.tsx
  src/middleware.ts
  src/util/cookieSetting.ts
Labels: Feat

#86 [PTTF-95] modalPotal 추가 및 폴더 구조 변경에 따른 코드 수정 그리고 Post 컴포넌트 수정
  src/app/user/employee/my-profile/page.tsx
  src/components/common/ApproveButtons.tsx
  src/components/common/Post/Post.tsx
  src/components/common/Post/SvgArrowComponent.tsx
  src/components/common/Post/Tooltip.tsx
Labels: Fix

#92 [PTTF-100] 눈에 밟히는 자잘한 버그 픽스
  src/app/user/employer/page.tsx
  src/app/user/noticeDetail/[noticeId]/[shopId]/page.tsx
  src/components/common/GNB.tsx
  src/components/common/StoreDetail/StoreDetailButtons.tsx
  src/components/common/StoreDetail/StoreDetailTypes.ts
  src/components/common/StoreDetail/index.tsx
  src/components/employer/EmployerNoticeForm.tsx
  src/components/employer/EmployerStoreDetail.tsx
  src/components/employer/Hook/useNoticeId.tsx
  src/components/employer/Hook/useShopId.tsx
  src/components/employer/PostEmployer.tsx
  src/components/employer/StoreEditForm.tsx
  src/components/employer/StoreRegisterForm.tsx
  src/util/constants/INPUT_VALUES.ts
  src/util/recentPostsLocalStorageLogic.ts
Labels: Fix

#93 [PTTF-101] 맞춤 공고에서 마감 공고 클릭 방지
  src/components/home/CustomNotice.tsx
Labels: Fix

#94 [PTTF-102] ♻️ middleware 버그 픽스
  src/middleware.ts
Labels: Feat

#95 [PTTF-103] Table 컴포넌트 소개란 호버 시 전체 소개 글이 뜨도록 수정
  src/components/common/SignModal.tsx
  src/components/common/Table.tsx
Labels: Feat, Fix

#97 [PTTF-105] 가게 관련 에러 제거
  src/app/user/employer/edit/page.tsx
  src/app/user/employer/notice/[noticeId]/edit/page.tsx
  src/app/user/employer/page.tsx
  src/components/common/SignModal.tsx
  src/components/employer/EmployerNoticeForm.tsx
  src/components/employer/EmployerStoreDetail.tsx
  src/components/employer/PostEmployer.tsx
  src/components/employer/StoreEditForm.tsx
  src/components/employer/StoreRegisterForm.tsx
Labels: Fix

#98 [PTTF-106] 프로필 등록 페이지 소개란 수정 및 post 컴포넌트 수정
  src/app/user/employee/my-profile/page.tsx
  src/app/user/employee/page.tsx
  src/components/common/ApproveButtons.tsx
  src/components/common/Post/Post.tsx
  src/components/common/SignModal.tsx
  src/components/common/Table.tsx
Labels: Fix

#99 👽️ Update README.md
  README.md
Labels: documentation

#102 👽️ Update README.md
  README.md
Labels: documentation

#100 Fix: 회원가입 로그인 페이지 및 모달창 관련 repactoring
  public/signin/logoIcon.svg
  public/signup/logoIcon.svg
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/app/user/employee/my-profile/page.tsx
  src/components/common/ApproveButtons.tsx
  src/components/common/Modal.tsx
  src/components/common/SignInput.tsx
  src/components/employer/EmployerNoticeForm.tsx
  src/components/employer/StoreEditForm.tsx
  src/components/employer/StoreRegisterForm.tsx
  src/components/signin/EmailInput.tsx
  src/components/signin/PasswordInput.tsx
  src/components/signup/ConfirmPasswordInput.tsx
  src/components/signup/EmailInput.tsx
  src/components/signup/PasswordInput.tsx
Labels: Fix

#106 [PTTF-110] refactor: signin페이지 컴포넌트 분리
  src/app/signin/page.tsx
  src/components/signin/ErrorModal.tsx
  src/components/signin/LoginForm.tsx
Labels: Fix

#110 [PTTF-114] 프로필 등록 페이지 재수정
  src/app/user/employee/page.tsx
Labels: Fix

#109 [PTTF-113] ✨ Add canceled notification
  src/components/common/NotificationModal/NOTIFICATION_API_RESPONSE_TYPE.ts
  src/components/common/NotificationModal/NotificationModalComponent.tsx
  src/components/common/NotificationModal/NotificationModalMessageBox.tsx
  tailwind.config.ts
Labels: Feat, Fix

#112 [PTTF-117] post 수정 및 페이지 카운트 문제 해결
  src/components/common/Post/Post.tsx
  src/components/home/FilterdNotice.tsx
  src/components/home/NoticeMain.tsx
Labels: Fix

#113 [PTTF-118] 남아있는 console제거
  src/app/apiTest/page.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/app/user/noticeDetail/[noticeId]/[shopId]/page.tsx
  src/components/common/Pagination.tsx
  src/components/employer/StoreEditForm.tsx
  src/middleware.ts
Labels: Fix

#114 [PTTF-119] 테이블 수정하여 거절 승인 클릭 시 바로 반영되도록 수정
  src/components/common/ApproveButtons.tsx
  src/components/common/EmployeeTable.tsx
  src/components/common/EmployerTable.tsx
  src/components/common/NotificationModal/NotificationModalComponent.tsx
  src/components/common/Table.tsx
  src/components/home/NoticeMain.tsx
Labels: Fix

#115 [PTTF-120] 배포링크 및 ppt 추가
  README.md
Labels: Fix
